
server:
  port: 8769

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

zuul:
  routes:
    #配置网关服务地址
    api-a:
      #如果访问/api-member开头就跳service-member服务
      path: /api-member/**
      service-id: service-member
    api-b:
      path: /api-order/**
      service-id: service-order
